"""Init

Revision ID: 73e8baf41c5e
Revises: aa7b6517dd07
Create Date: 2023-03-05 12:00:45.500767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73e8baf41c5e'
down_revision = 'aa7b6517dd07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
