# Generated by Django 4.1.6 on 2023-02-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pescription', models.CharField(max_length=350)),
                ('path', models.ImageField(upload_to='uploads')),
            ],
        ),
    ]
